site_name: {{ cookiecutter.name | jsonify }}
repo_url: {{ cookiecutter.repo | jsonify }}
theme:
    name: mkdocs
    highlightjs: true
    palette:
      primary: light-blue
nav:
  - Introduction: 'index.md'
plugins:
  - techdocs-core
